// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cardclubs8_l
// Size: 64 x 32
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cardclubs8_l_H_
#define _cardclubs8_l_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cardclubs8_l)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cardclubs8_l;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cardclubs8_l_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {64 , 0  , 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // cardclubs8_l_mesh_0

ImgSeg_t cardclubs8_l_components[] = {
  {
    _cardclubs8_lSegmentRomStart + 0,
    _cardclubs8_lSegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardclubs8_l_mesh_0
  }
}; // cardclubs8_l_components

Img_t cardclubs8_l = {
  sizeof(cardclubs8_l_components)/sizeof(cardclubs8_l_components[0]),
  cardclubs8_l_components,
  64, 32,

  G_TF_BILERP
}; // cardclubs8_l

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cardclubs8_l_H_
