// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cardheartsk_l
// Size: 64 x 32
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cardheartsk_l_H_
#define _cardheartsk_l_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cardheartsk_l)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cardheartsk_l;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cardheartsk_l_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {64 , 0  , 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // cardheartsk_l_mesh_0

ImgSeg_t cardheartsk_l_components[] = {
  {
    _cardheartsk_lSegmentRomStart + 0,
    _cardheartsk_lSegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardheartsk_l_mesh_0
  }
}; // cardheartsk_l_components

Img_t cardheartsk_l = {
  sizeof(cardheartsk_l_components)/sizeof(cardheartsk_l_components[0]),
  cardheartsk_l_components,
  64, 32,

  G_TF_BILERP
}; // cardheartsk_l

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cardheartsk_l_H_
