// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cardhearts9
// Size: 64 x 87
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cardhearts9_H_
#define _cardhearts9_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cardhearts9)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cardhearts9;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cardhearts9_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , 0  , 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}}
}; // cardhearts9_mesh_0

Vtx cardhearts9_mesh_1[] = {
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , -64, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {0  , -64, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}}
}; // cardhearts9_mesh_1

Vtx cardhearts9_mesh_2[] = {
    {.v = {.ob = {0  , -64, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , -64, 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {64 , -87, 0}, .flag = 0, .tc = {64 <<6, 23 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}},
    {.v = {.ob = {0  , -87, 0}, .flag = 0, .tc = {0  <<6, 23 <<6}, .cn = {0xf1, 0xf1, 0xf1, 0xff}}}
}; // cardhearts9_mesh_2

ImgSeg_t cardhearts9_components[] = {
  {
    _cardhearts9SegmentRomStart + 0,
    _cardhearts9SegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardhearts9_mesh_0
  },
  {
    _cardhearts9SegmentRomStart + 4096,
    _cardhearts9SegmentRomStart + 8192,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardhearts9_mesh_1
  },
  {
    _cardhearts9SegmentRomStart + 8192,
    _cardhearts9SegmentRomStart + 11136,
    64, 23,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardhearts9_mesh_2
  }
}; // cardhearts9_components

Img_t cardhearts9 = {
  sizeof(cardhearts9_components)/sizeof(cardhearts9_components[0]),
  cardhearts9_components,
  64, 87,

  G_TF_BILERP
}; // cardhearts9

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cardhearts9_H_
