// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: carddiamonds10_l
// Size: 64 x 32
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _carddiamonds10_l_H_
#define _carddiamonds10_l_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(carddiamonds10_l)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t carddiamonds10_l;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx carddiamonds10_l_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {64 , 0  , 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // carddiamonds10_l_mesh_0

ImgSeg_t carddiamonds10_l_components[] = {
  {
    _carddiamonds10_lSegmentRomStart + 0,
    _carddiamonds10_lSegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    carddiamonds10_l_mesh_0
  }
}; // carddiamonds10_l_components

Img_t carddiamonds10_l = {
  sizeof(carddiamonds10_l_components)/sizeof(carddiamonds10_l_components[0]),
  carddiamonds10_l_components,
  64, 32,

  G_TF_BILERP
}; // carddiamonds10_l

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _carddiamonds10_l_H_
