// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cardspadesa_l
// Size: 64 x 32
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cardspadesa_l_H_
#define _cardspadesa_l_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cardspadesa_l)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cardspadesa_l;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cardspadesa_l_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {64 , 0  , 0}, .flag = 0, .tc = {64 <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {64 , -32, 0}, .flag = 0, .tc = {64 <<6, 32 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 32 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // cardspadesa_l_mesh_0

ImgSeg_t cardspadesa_l_components[] = {
  {
    _cardspadesa_lSegmentRomStart + 0,
    _cardspadesa_lSegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cardspadesa_l_mesh_0
  }
}; // cardspadesa_l_components

Img_t cardspadesa_l = {
  sizeof(cardspadesa_l_components)/sizeof(cardspadesa_l_components[0]),
  cardspadesa_l_components,
  64, 32,

  G_TF_BILERP
}; // cardspadesa_l

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cardspadesa_l_H_
