// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cdown
// Size: 16 x 16
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cdown_H_
#define _cdown_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cdown)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cdown;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cdown_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {16 , 0  , 0}, .flag = 0, .tc = {16 <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {16 , -16, 0}, .flag = 0, .tc = {16 <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // cdown_mesh_0

ImgSeg_t cdown_components[] = {
  {
    _cdownSegmentRomStart + 0,
    _cdownSegmentRomStart + 512,
    16, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cdown_mesh_0
  }
}; // cdown_components

Img_t cdown = {
  sizeof(cdown_components)/sizeof(cdown_components[0]),
  cdown_components,
  16, 16,

  G_TF_BILERP
}; // cdown

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cdown_H_
