// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cleft
// Size: 16 x 16
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cleft_H_
#define _cleft_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cleft)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cleft;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cleft_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {16 , 0  , 0}, .flag = 0, .tc = {16 <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {16 , -16, 0}, .flag = 0, .tc = {16 <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // cleft_mesh_0

ImgSeg_t cleft_components[] = {
  {
    _cleftSegmentRomStart + 0,
    _cleftSegmentRomStart + 512,
    16, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cleft_mesh_0
  }
}; // cleft_components

Img_t cleft = {
  sizeof(cleft_components)/sizeof(cleft_components[0]),
  cleft_components,
  16, 16,

  G_TF_BILERP
}; // cleft

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cleft_H_
