// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: cright
// Size: 16 x 16
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _cright_H_
#define _cright_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(cright)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t cright;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx cright_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {16 , 0  , 0}, .flag = 0, .tc = {16 <<6, 0  <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {16 , -16, 0}, .flag = 0, .tc = {16 <<6, 16 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // cright_mesh_0

ImgSeg_t cright_components[] = {
  {
    _crightSegmentRomStart + 0,
    _crightSegmentRomStart + 512,
    16, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    cright_mesh_0
  }
}; // cright_components

Img_t cright = {
  sizeof(cright_components)/sizeof(cright_components[0]),
  cright_components,
  16, 16,

  G_TF_BILERP
}; // cright

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _cright_H_
