// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: enterdonsol
// Size: 128 x 32
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _enterdonsol_H_
#define _enterdonsol_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(enterdonsol)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t enterdonsol;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx enterdonsol_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, 0  , 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -16, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // enterdonsol_mesh_0

Vtx enterdonsol_mesh_1[] = {
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -16, 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -32, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // enterdonsol_mesh_1

ImgSeg_t enterdonsol_components[] = {
  {
    _enterdonsolSegmentRomStart + 0,
    _enterdonsolSegmentRomStart + 4096,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    enterdonsol_mesh_0
  },
  {
    _enterdonsolSegmentRomStart + 4096,
    _enterdonsolSegmentRomStart + 8192,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    enterdonsol_mesh_1
  }
}; // enterdonsol_components

Img_t enterdonsol = {
  sizeof(enterdonsol_components)/sizeof(enterdonsol_components[0]),
  enterdonsol_components,
  128, 32,

  G_TF_BILERP
}; // enterdonsol

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _enterdonsol_H_
