// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: eye1
// Size: 128 x 67
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _eye1_H_
#define _eye1_H_

#include <xo-types.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(eye1)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t eye1;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx eye1_mesh_0[] = {
    {.v = {.ob = {0  , 0  , 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, 0  , 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -16, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // eye1_mesh_0

Vtx eye1_mesh_1[] = {
    {.v = {.ob = {0  , -16, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -16, 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -32, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // eye1_mesh_1

Vtx eye1_mesh_2[] = {
    {.v = {.ob = {0  , -32, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -32, 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -48, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -48, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // eye1_mesh_2

Vtx eye1_mesh_3[] = {
    {.v = {.ob = {0  , -48, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -48, 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -64, 0}, .flag = 0, .tc = {128<<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -64, 0}, .flag = 0, .tc = {0  <<6, 16 <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // eye1_mesh_3

Vtx eye1_mesh_4[] = {
    {.v = {.ob = {0  , -64, 0}, .flag = 0, .tc = {0  <<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -64, 0}, .flag = 0, .tc = {128<<6, 0  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {128, -67, 0}, .flag = 0, .tc = {128<<6, 3  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}},
    {.v = {.ob = {0  , -67, 0}, .flag = 0, .tc = {0  <<6, 3  <<6}, .cn = {0x00, 0x00, 0x00, 0x00}}}
}; // eye1_mesh_4

ImgSeg_t eye1_components[] = {
  {
    _eye1SegmentRomStart + 0,
    _eye1SegmentRomStart + 4096,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    eye1_mesh_0
  },
  {
    _eye1SegmentRomStart + 4096,
    _eye1SegmentRomStart + 8192,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    eye1_mesh_1
  },
  {
    _eye1SegmentRomStart + 8192,
    _eye1SegmentRomStart + 12288,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    eye1_mesh_2
  },
  {
    _eye1SegmentRomStart + 12288,
    _eye1SegmentRomStart + 16384,
    128, 16,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    eye1_mesh_3
  },
  {
    _eye1SegmentRomStart + 16384,
    _eye1SegmentRomStart + 17152,
    128, 3,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    eye1_mesh_4
  }
}; // eye1_components

Img_t eye1 = {
  sizeof(eye1_components)/sizeof(eye1_components[0]),
  eye1_components,
  128, 67,

  G_TF_BILERP
}; // eye1

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _eye1_H_
