// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: heart_ace
// Size: 64 x 92
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _heart_ace_H_
#define _heart_ace_H_

#include <PR/ultratypes.h>
#include <xo-img.h>

#include "xo-spec.h"

xo_spec_DeclareRomSegment(heart_ace)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t heart_ace;
#else // GENERATED_IMAGE_DECLARATIONS
#include "xo-render.h"

ImgSeg_t heart_ace_components[] = {
  {
    _heart_aceSegmentRomStart,
    _heart_aceSegmentRomEnd,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR
  },
  {
    _heart_aceSegmentRomStart,
    _heart_aceSegmentRomEnd,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR
  },
  {
    _heart_aceSegmentRomStart,
    _heart_aceSegmentRomEnd,
    64, 28,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR
  }
}; // heart_ace_components

Img_t heart_ace = {
  sizeof(heart_ace_components)/sizeof(heart_ace_components[0]),
  heart_ace_components,

  G_TF_POINT
}; // heart_ace

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _heart_ace_H_
