// Generated by xo-tt64.
// A tool by xoorath.
//
// Name: test_joker
// Size: 64 x 92
// Type: 16-Bit RGBA (OUTFMT_RGBA_16)

#ifndef _test_joker_H_
#define _test_joker_H_

#include <PR/ultratypes.h>
#include <xo-img.h>

#include <xo-spec.h>

xo_spec_DeclareRomSegment(test_joker)

#ifndef GENERATED_IMAGE_DECLARATIONS
extern Img_t test_joker;
#else // GENERATED_IMAGE_DECLARATIONS
#include <xo-render.h>
#include <PR/gbi.h>

Vtx test_joker_mesh_0[] = {
    {.v = {.ob = {  0,   0, 0}, .flag = 0, .tc = {  0<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64,   0, 0}, .flag = 0, .tc = { 64<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64, -32, 0}, .flag = 0, .tc = { 64<<6,  32<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {  0, -32, 0}, .flag = 0, .tc = {  0<<6,  32<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // test_joker_mesh_0

Vtx test_joker_mesh_1[] = {
    {.v = {.ob = {  0, -32, 0}, .flag = 0, .tc = {  0<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64, -32, 0}, .flag = 0, .tc = { 64<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64, -64, 0}, .flag = 0, .tc = { 64<<6,  32<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {  0, -64, 0}, .flag = 0, .tc = {  0<<6,  32<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // test_joker_mesh_1

Vtx test_joker_mesh_2[] = {
    {.v = {.ob = {  0, -64, 0}, .flag = 0, .tc = {  0<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64, -64, 0}, .flag = 0, .tc = { 64<<6,   0<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = { 64, -92, 0}, .flag = 0, .tc = { 64<<6,  28<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}},
    {.v = {.ob = {  0, -92, 0}, .flag = 0, .tc = {  0<<6,  28<<6}, .cn = {0xff, 0xff, 0xff, 0xff}}}
}; // test_joker_mesh_2

ImgSeg_t test_joker_components[] = {
  {
    _test_jokerSegmentRomStart + 0,
    _test_jokerSegmentRomStart + 4096,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    test_joker_mesh_0
  },
  {
    _test_jokerSegmentRomStart + 4096,
    _test_jokerSegmentRomStart + 8192,
    64, 32,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    test_joker_mesh_1
  },
  {
    _test_jokerSegmentRomStart + 8192,
    _test_jokerSegmentRomStart + 11776,
    64, 28,
    G_TX_CLAMP | G_TX_NOMIRROR, G_TX_CLAMP | G_TX_NOMIRROR,
    NULL,
    test_joker_mesh_2
  }
}; // test_joker_components

Img_t test_joker = {
  sizeof(test_joker_components)/sizeof(test_joker_components[0]),
  test_joker_components,
  64, 92,

  G_TF_BILERP
}; // test_joker

#endif // GENERATED_IMAGE_DECLARATIONS

#endif // _test_joker_H_
