#include <cardclubs2.h>
#include <cardclubs3.h>
#include <cardclubs4.h>
#include <cardclubs5.h>
#include <cardclubs6.h>
#include <cardclubs7.h>
#include <cardclubs8.h>
#include <cardclubs9.h>
#include <cardclubs10.h>
#include <cardclubsa.h>
#include <cardclubsj.h>
#include <cardclubsq.h>
#include <cardclubsk.h>

#include <carddiamonds2.h>
#include <carddiamonds3.h>
#include <carddiamonds4.h>
#include <carddiamonds5.h>
#include <carddiamonds6.h>
#include <carddiamonds7.h>
#include <carddiamonds8.h>
#include <carddiamonds9.h>
#include <carddiamonds10.h>
#include <carddiamondsa.h>
#include <carddiamondsj.h>
#include <carddiamondsq.h>
#include <carddiamondsk.h>

#include <cardhearts2.h>
#include <cardhearts3.h>
#include <cardhearts4.h>
#include <cardhearts5.h>
#include <cardhearts6.h>
#include <cardhearts7.h>
#include <cardhearts8.h>
#include <cardhearts9.h>
#include <cardhearts10.h>
#include <cardheartsa.h>
#include <cardheartsj.h>
#include <cardheartsq.h>
#include <cardheartsk.h>

#include <cardspades2.h>
#include <cardspades3.h>
#include <cardspades4.h>
#include <cardspades5.h>
#include <cardspades6.h>
#include <cardspades7.h>
#include <cardspades8.h>
#include <cardspades9.h>
#include <cardspades10.h>
#include <cardspadesa.h>
#include <cardspadesj.h>
#include <cardspadesq.h>
#include <cardspadesk.h>